# Generated by Django 4.1.1 on 2022-12-15 11:20

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('fichamedica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='Data_Admissao',
            field=models.DateTimeField(validators=[verificacao.validator.validate_data]),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='Localizacao_Fisica',
            field=models.CharField(error_messages={'unique': 'Localização já cadastrada, insira outra'}, max_length=8, unique=True, validators=[verificacao.validator.validate_localizacao]),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='Numero_Ficha',
            field=models.CharField(error_messages={'unique': 'Número de Ficha já cadastrado, insira outro'}, max_length=5, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_numeroficha]),
        ),
    ]
